nelmio_cors:
    defaults:
        origin_regex: true
        allow_origin: ['*'] # Temporairement permissif pour tests
        allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']
        allow_headers: ['*']
        expose_headers: [ 'Authorization', 'Content-Type' ]
        max_age: 3600
        allow_credentials: true