nelmio_cors:
    defaults:
        origin_regex: false  # Désactivé pour plus de fiabilité
        allow_origin: ['https://games-ticket.netlify.app']  # Testez en dur d'abord
        allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS', 'PATCH']
        allow_headers: ['*']  # Permettre temporairement tout pour tester
        expose_headers: ['*']
        max_age: 0  # Désactive le cache CORS pendant les tests
        allow_credentials: false  # Désactivé temporairement