nelmio_cors:
    defaults:
        allow_credentials: true
        allow_origin: ['https://games-ticket.netlify.app']
        allow_headers: ['Content-Type', 'Authorization', 'X-Requested-With']
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'DELETE']
        expose_headers: ['Link', 'Authorization']
        max_age: 3600
    paths:
        '^/': # Applique à toutes les routes
            allow_origin: ['https://games-ticket.netlify.app']
            allow_headers: ['Content-Type', 'Authorization', 'X-Requested-With']
            allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'DELETE']
            expose_headers: ['Link', 'Authorization']
            max_age: 3600
