nelmio_cors:
    defaults:
        origin_regex: true
        allow_origin: ['^https://games-ticket\.netlify\.app$']
        allow_headers: ['Content-Type', 'Authorization', 'X-Requested-With']
        allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']
        expose_headers: ['Content-Type', 'Authorization']
        max_age: 3600
        allow_credentials: false
    paths:
        '^/api': ~