nelmio_cors:
    defaults:
        allow_origin: ['http://localhost:3000', 'https://games-ticket-frontend.netlify.app']
        allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']
        allow_headers: ['Content-Type', 'Authorization', 'X-Requested-With']
        expose_headers: ['Content-Type', 'Authorization']
        max_age: 3600
        allow_credentials: true
    paths:
        '^/':
            origin_regex: true
