security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern: ^/api/login$
            stateless: true
            security: false

        register:
            pattern: ^/api/users/register
            stateless: true
            security: false

    #    public:
    #        pattern: ^/api/offers$
    #        stateless: true
     #       security: false

        main:
            lazy: true
            provider: app_user_provider
            stateless: true
            jwt: ~
            entry_point: jwt

    access_control:
        - { path: ^/api/login$, roles: IS_AUTHENTICATED_ANONYMOUSLY, methods: [ POST ] }
        - { path: ^/api/users/register, roles: IS_AUTHENTICATED_ANONYMOUSLY, methods: [ POST ] }

        # GET public
        - { path: ^/api/offers$, roles: IS_AUTHENTICATED_ANONYMOUSLY, methods: [ GET ] }
        - { path: ^/api/offers/$, roles: IS_AUTHENTICATED_ANONYMOUSLY, methods: [ GET ] }


        # POST/PUT/DELETE réservés à ROLE_ADMIN
        - { path: ^/api/offers$, roles: ROLE_ADMIN, methods: [ POST, PUT, DELETE ] }

        # Authentification requise pour toute l’API restante
        - { path: ^/api, roles: IS_AUTHENTICATED_FULLY }







