### Login Admin
POST http://localhost:8000/api/login
Content-Type: application/json

{
  "email": "admin@example.com",
  "password": "Admin@123"
}
### Login Admin 2
POST http://localhost:8000/api/login
Content-Type: application/json

{
  "email": "master@example.com",
  "password": "Master@123"
}

### Login User
POST http://localhost:8000/api/login
Content-Type: application/json

{
  "email": "koffi@example.com",
  "password": "Koffi123!"
}

### Login Controller
POST http://localhost:8000/api/login
Content-Type: application/json

{
  "email": "controller@example.com",
  "password": "Control@123"
}

### Get All Offers (Requires JWT)
GET http://games-ticket-backend-f3af92d920b6.herokuapp.com/api/offers
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE3NDg1MDkzMTksImV4cCI6MTc0ODUxMjkxOSwicm9sZXMiOlsiUk9MRV9BRE1JTiIsIlJPTEVfVVNFUiJdLCJ1c2VybmFtZSI6ImFkbWluQGV4YW1wbGUuY29tIn0.VQJ-nH5rCvSvI-sthTBiGgDYmRU6CT8tZWx0rs-B89fPJstn_fO5DH-ZtZ8thOs50Ze1mOP14o4Ucvg9sDqXos-WBH_9uCoLw262NZjKW4J2PR9y6MB519OIl_Crt_tA0xYOymeOGcO0BrXIxPWOeIWpo1y98ZU46cMQotOpQGh0hGM0RPUglgN2XJCzNQ5Sma8jjE8S2OLordiTttQCHJ5xjuKJUhQXM0uKstpin5UquxaqbvlVGxQUB6Qha47rmEGi3sSEke75GVPziIhHdbB4XM7eZr8xd48ohYC_JbFqi_vu0pmfxP1mM3leKR02qn858xiRhY1itXlYlzP-pg

### Create Offer (Requires JWT)
POST http://localhost:8000/api/offers
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE3NDc0MDI3NTIsImV4cCI6MTc0NzQwNjM1Miwicm9sZXMiOlsiUk9MRV9BRE1JTiIsIlJPTEVfVVNFUiJdLCJ1c2VybmFtZSI6Im1hc3RlckBleGFtcGxlLmNvbSJ9.bdguBQmR57ot7cC_Q4981WDNrUkmOKCYtoHnLOfHhwoU2cgkEIloVW9JpLC834Ow98bI6hB_HNLKBhGTA1ZGdkS5hAFzeHDg3c3HPqqwYt6cnXETXqNrgcANEG61s3JFSMvmu-50gTjVVYnpiDgUIJSj4QER0o1A5cLu3oPSSHnYW8Ck7B6NBnbVw85Ux08XkjXAUZ5HaKlVTARxpHshLfwkCkLJ0x0b1-s2hN2goP8-mSWExH55f9u_MuaHmaehB89mZoRIuW9-kTX5uzr2UD9I1yuPaG9YL7QzxqknJpOK-dHSh53cw40zXFSYBZzjfKDM3-O3cL7_9vS1pQLQLw


{
  "name": "Offre Famille",
  "description": "Quatre personnes",
  "price": 1200,
  "max_people": 5000
}

### Get All Users (Requires Admin JWT)
GET http://localhost:8000/api/users
Authorization: Bearer {{JWT}}

### Créer un nouvel utilisateur
POST http://127.0.0.1:8000/api/users/register
Content-Type: application/json

{
  "first_name": "Michel",
  "last_name": "Durand",
  "email": "michel.durand@example.com",
  "password": "Michel@2024"
}


### Verify Ticket (Requires Controller JWT)
GET http://localhost:8000/api/orders/verify-ticket/1234567890
Authorization: Bearer {{JWT}}

### Création utilisateur de test
POST http://localhost:8000/api/users/register
Content-Type: application/json

{
  "first_name": "Test",
  "last_name": "User",
  "email": "authtest@example.com",
  "password": "Test@123"
}

### Création utilisateur
POST http://127.0.0.1:8000/api/users/register
Content-Type: application/json

{
"first_name": "Scan",
"last_name": "Test",
"email": "scan.test@example.com",
"password": "Scan@123"
}
### Création utilisateur admin
POST http://127.0.0.1:8000/api/users/register
Content-Type: application/json

{
  "first_name": "Master",
  "last_name": "myname",
  "email": "master@example.com",
  "password": "Master@123",
  "roles": ["ROLE_ADMIN"]
}


###
POST http://127.0.0.1:8000/api/users/register
Content-Type: application/json

{
"first_name": "Jean",
"last_name": "Dupont",
"email": "jean.dupont@example.com",
"password": "Jean@1234"
}
### Authentification utilisateur
POST http://localhost:8000/api/login
Content-Type: application/json

{
  "email": "michel.durand@example.com",
  "password": "Michel@2024"
}




### Tester l'affichage des offres (publique, sans authentification)
GET http://127.0.0.1:8000/api/offers
Accept: application/json

### Récupérer les commandes de l'utilisateur connecté (ROLE_USER)
GET http://127.0.0.1:8000/api/orders
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE3NDc0NjgwNjIsImV4cCI6MTc0NzQ3MTY2Miwicm9sZXMiOlsiUk9MRV9VU0VSIl0sInVzZXJuYW1lIjoia29mZmlAZXhhbXBsZS5jb20ifQ.HQsJTDI9Z15RWwGT-PSiB-CVyMOai2AP3e7RlWL3EPKLuNp4nbEcudPoxm8WMKAijEx4ybihJXObpOvaEqi0Vewy0Wo1eVartDpMbg_D2VXuLf2nrIS5W3fcfh-3V97DqQgW0LGtdjYl08xlClDV3rI72920Qem_f42u6x2qYJKnbUFbBTkx6y7NVcSJ2wACu8VQ6tQthPLhBApZdUrBylJS1VV6_YKknqSkCra0FaDYBbCaRSJYXIxkN5eiMJm0VW4Zxc8wyJK5aHxRASvPvKlTG4fiY0PKTHj8edKfOFczQW1gu_AKoIVaKxSBzN9MGoCmTzfaAN2hESRFgQIFZw

Accept: application/json


### Login Admin
POST http://games-ticket-backend-f3af92d920b6.herokuapp.com/api/login
Content-Type: application/json

{
  "email": "admin@example.com",
  "password": "Admin@123"
}

### Create Offer (Requires JWT)
POST http://games-ticket-backend-f3af92d920b6.herokuapp.com/api/offers
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE3NDg1MDkzMTksImV4cCI6MTc0ODUxMjkxOSwicm9sZXMiOlsiUk9MRV9BRE1JTiIsIlJPTEVfVVNFUiJdLCJ1c2VybmFtZSI6ImFkbWluQGV4YW1wbGUuY29tIn0.VQJ-nH5rCvSvI-sthTBiGgDYmRU6CT8tZWx0rs-B89fPJstn_fO5DH-ZtZ8thOs50Ze1mOP14o4Ucvg9sDqXos-WBH_9uCoLw262NZjKW4J2PR9y6MB519OIl_Crt_tA0xYOymeOGcO0BrXIxPWOeIWpo1y98ZU46cMQotOpQGh0hGM0RPUglgN2XJCzNQ5Sma8jjE8S2OLordiTttQCHJ5xjuKJUhQXM0uKstpin5UquxaqbvlVGxQUB6Qha47rmEGi3sSEke75GVPziIhHdbB4XM7eZr8xd48ohYC_JbFqi_vu0pmfxP1mM3leKR02qn858xiRhY1itXlYlzP-pg


{
  "name": "Offre TEST",
  "description": "requests.http",
  "price": 1200,
  "max_people": 5000
}
### Create Offer (sans Requires JWT)
POST http://games-ticket-backend-f3af92d920b6.herokuapp.com/api/offers
Content-Type: application/json


{
  "name": "Offre TEST",
  "description": "requests.http",
  "price": 1200,
  "max_people": 5000
}

### TEST CREATION OFFRE
POST https://games-ticket-backend-f3af92d920b6.herokuapp.com/api/offers/create
Content-Type: application/json

{
"name": "Test distinct route",
"description": "test",
"price": 123,
"max_people": 20
}
