nelmio_cors:
    defaults:
        origin_regex: true
        allow_origin: ['^https?://localhost:[0-9]+$', '^https://games-ticket-frontend\.netlify\.app$']
        allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']
        allow_headers: ['Content-Type', 'Authorization', 'X-Requested-With']
        expose_headers: ['*']
        max_age: 3600
        allow_credentials: true
    paths:
        '^/api': # Toutes vos routes API
            allow_origin: ['*'] # Temporaire pour debug
            allow_headers: ['*']
            allow_methods: ['*']