nelmio_cors:
    defaults:
        origin_regex: true
        allow_origin: ['^http://localhost:[0-9]+$', '^https://.*\.netlify\.app$', 'https://games-ticket-frontend.netlify.app']
        allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']
        allow_headers: ['*']
        expose_headers: ['Authorization', 'Content-Type']
        max_age: 3600
        allow_credentials: true
